# Site settings
title: Chen Sun
general_email: chensunx@gmail.com
#academic_email: your_academic_email@univ

description: > # this means to ignore newlines until "baseurl:"
  TODO description

#baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

#url: "https://ys1998.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
#github_username: github_username
linkedin_username: chensunx
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
